spring:
  application:
    name: Inventory Service Demo
  data:
    mongodb:
      uri: mongodb+srv://root:root@cluster0.m7dnzbv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: products-db
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-d8rm3bg4cwywnjin.eu.auth0.com/
logging:
  level:
    sun:
      rmi:
        transport:
          tcp: OFF
server:
  port: 8081